config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get 'dashboard', to: 'employees#dashboard'
  post 'import', to: 'employees#import'
  get 'export', to: 'employees#export'
  # Defines the root path route ("/")
  root "employees#dashboard"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/employee.rb
class Employee < ApplicationRecord
  scope :filter_by_state, ->(name) { where('lower(state) = ?', name.downcase).first }

  STATES = %w[India UAE]

  # def import
  #   xlsx = Roo::Excelx.new(file)

  #   data = []

  #   xlsx.each_row_streaming(offset: 1) do |row|
  #     site = row[0].value
  #     permanent = row[1].value.to_i
  #     contract = row[2].value.to_i
  #     permanent_male = row[3].value.to_i
  #     permanent_female = row[4].value.to_i
  #     contract_male = row[5].value.to_i
  #     contract_female = row[6].value.to_i
  #     overall_workforce = row[7].value.to_i
  #     male_female_ratio = row[8].value

  #     data << {
  #       site:,
  #       permanent:,
  #       contract:,
  #       permanent_male:,
  #       permanent_female:,
  #       contract_male:,
  #       contract_female:,
  #       overall_workforce:,
  #       male_female_ratio:
  #     }
  #   end
  # end

  def self.to_csv
    CSV.generate do |csv|
      csv << column_names
      all.each do |employee|
        csv << employee.attributes.values_at(*column_names)
      end
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_file, only: :import

  def dashboard
    india_and_uae_states = Employee::STATES
    india_and_uae_employees = Employee.where(state: india_and_uae_states)

    india_employees = india_and_uae_employees.filter_by_state('India')
    uae_employees = india_and_uae_employees.filter_by_state('UAE')

    @employee_chart_data = generate_employee_chart_data(india_employees, uae_employees)

  end

  def import
    success, response_message = read_employee_counts_from_xlsx_file
    if success
      flash[:notice] = response_message
    else
      flash[:error] = response_message
    end
    redirect_to root_path
  end

  def export
    @employees = Employee.all

    respond_to do |format|
      format.html
      format.json { render json: @employees }
      format.csv { send_data @employees.to_csv, filename: "employees-#{Date.today}.csv" }
    end
  end

  private

  def read_employee_counts_from_xlsx_file
    xlsx = Roo::Excelx.new(@file.path)

    employee_attrs = []
    errors = []

    # Keep track of states that have already been seen to detect duplicates
    states_seen = Set.new

    xlsx.each_row_streaming(offset: 2) do |row|
      state, permanent, contract, permanent_male, permanent_female, contract_male, contract_female = row.map(&:value)
      next if state.blank?

      # Check for duplicates
      if states_seen.include?(state)
        errors << "Duplicate data detected for state '#{state}'. Skipping this row."
        next
      else
        states_seen.add(state)
      end

      overall_workforce = permanent.to_i + contract.to_i
      total_male_employees = permanent_male.to_i + contract_male.to_i
      total_female_employees = permanent_female.to_i + contract_female.to_i

      if overall_workforce.zero? || total_male_employees.zero? || total_female_employees.zero?
        errors << "Invalid data detected for state '#{state}'. Skipping this row."
        next
      end

      male_female_ratio = (total_male_employees.to_f / total_female_employees).round(2)
      employee_attrs << {
        state:,
        permanent: permanent.to_i,
        contract: contract.to_i,
        permanent_male: permanent_male.to_i,
        permanent_female: permanent_female.to_i,
        contract_male: contract_male.to_i,
        contract_female: contract_female.to_i,
        overall_workforce:,
        male_female_ratio: "#{male_female_ratio}:1"
      }
    end

    Employee.upsert_all(employee_attrs, unique_by: :state)
    if errors.empty?
      [true, 'Employees successfully imported.']
    else
      [false, errors]
    end
  end

  def generate_employee_chart_data(india_employees, uae_employees)
    (Employee.column_names - ["id", "state", "created_at", "updated_at"]).map do |column|
      {
        name: column.titleize,
        data: {
          'India': india_employees.try(column.to_sym) || 0,
          'UAE': uae_employees.try(column.to_sym) || 0
        }
      }
    end
  end

  def set_file
    @file = params[:excel_file]
  end

end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/employees_helper.rb
# frozen_string_literal: true

module EmployeesHelper
end

app/views/employees/_import_file_form.html.erb
<%= form_with url: { controller: "employees", action: "import" }, html: { multipart: true } do |f| %>
  <%= label_tag :excel_file, "Select an Excel File: " %>
  <%= f.file_field :excel_file, id: :excel_file, accept: ".xlsx", required: true %>
  <%= f.submit 'Import' %>
<% end %>

app/views/employees/dashboard.html.erb
<%= render 'import_file_form' %>
<br><br>
<%= link_to 'Export CSV', export_path(format: 'csv') %>
<%= link_to 'Export JSON', export_path(format: 'json') %>


<h2>Graphs</h2>


<h1>Employee Count <%= Employee::STATES.join(' Vs ') %></h1>

<h4>Column Chart Stacked</h4>
<%= column_chart @employee_chart_data, stacked: true %>

<h4>Bar Chart</h4>
<%= bar_chart @employee_chart_data, stacked: true %>

<h4>Column Chart</h4>
<%= column_chart @employee_chart_data %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EmployeeReport</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% flash.each do |name, messages| %>
      <div class="alert alert-<%= name %>">

      <ul>
      <% messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>

      </div>
    <% end %>
    <%= yield %>
  </body>
</html>